[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bangla-multiscript"
version = "1.0.0"
authors = [
  { name="Shahriar", email="shahriarhossain1837@gmail.com" },
]
description = "High-Throughput Bengali to Natural Avro Banglish & Urban Code-Mixed Alignment Engine"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Text Processing :: Linguistic",
]

[project.urls]
"Homepage" = "https://github.com/ShahriarParib/BanglaMultiScript"
"Bug Tracker" = "https://github.com/ShahriarParib/BanglaMultiScript/issues"

[project.scripts]
bangla-multiscript = "bangla_multiscript.cli:main"
