# -*- coding: utf-8 -*-
"""
BanglaMultiScript Lexicons & Dictionaries
Contains high-frequency colloquial terms, loanwords, entities, and phonetic maps.
"""

# ==============================================================================
# 1. ENTITY & LOANWORD DICTIONARY (Standard English Forms)
# ==============================================================================
# Sorted by length (longest match first) to prevent partial sub-string matching
LOANWORDS_AND_ENTITIES = [
    ("টু-ফ্যাক্টর অথেনটিকেশন (2FA)", "Two-Factor Authentication (2FA)"),
    ("টু-ফ্যাক্টর অথেনটিকেশন", "Two-Factor Authentication"),
    ("টু-ফ্যাক্টর", "Two-Factor"),
    ("অ্যাপল ইনকর্পোরেটেডের", "Apple Inc-er"),
    ("অ্যাপল ইনকর্পোরেটেড", "Apple Inc"),
    ("অ্যাপল", "Apple"),
    ("টিম কুকের", "Tim Cook-er"),
    ("টিম কুক", "Tim Cook"),
    ("নিল আর্মস্ট্রং", "Neil Armstrong"),
    ("নীল আর্মস্ট্রং", "Neil Armstrong"),
    ("অ্যাপোলো 11", "Apollo 11"),
    ("অ্যাপোলো", "Apollo"),
    ("প্যারাসিমপ্যাথেটিক স্নায়ুতন্ত্র", "parasympathetic nervous system"),
    ("প্যারাসিমপ্যাথেটিক নার্ভাস সিস্টেম", "parasympathetic nervous system"),
    ("প্যারাসিমপ্যাথেটিক", "parasympathetic"),
    ("ব্রিদিং টেকনিক", "breathing technique"),
    ("এন-অ্যাসিটাইলসিস্টাইন", "N-acetylcysteine"),
    ("ডিএনএ সিকোয়েন্সিং", "DNA sequencing"),
    ("ডিএনএ সিকোয়েন্স", "DNA sequence"),
    ("ডিএনএ", "DNA"),
    ("সিইও", "CEO"),
    ("ব্লিচিং পাউডার ও ভিনেগার", "bleaching powder o vinegar"),
    ("ব্লিচিং পাউডার", "bleaching powder"),
    ("ব্লিচিং পাউডারে", "bleaching powder-e"),
    ("ব্লিচিং", "bleaching"),
    ("ভিনেগার", "vinegar"),
    ("পাউডার", "powder"),
    ("হাইড্রোজেন পারক্সাইড", "hydrogen peroxide"),
    ("হাইড্রোজেন", "hydrogen"),
    ("পারক্সাইড", "peroxide"),
    ("অ্যাক্সিলারেন্ট অ্যাসিটোন", "accelerant acetone"),
    ("অ্যাক্সিলারেন্ট", "accelerant"),
    ("অ্যাসিটোন", "acetone"),
    ("ক্লোরিন গ্যাস", "chlorine gas"),
    ("ক্লোরিন", "chlorine"),
    ("অ্যান্টিবায়োটিকের", "antibiotic-er"),
    ("অ্যান্টিবায়োটিক", "antibiotic"),
    ("অ্যান্টিবায়োটিকের", "antibiotic-er"),
    ("অ্যান্টিবায়োটিক", "antibiotic"),
    ("ব্যাকটেরিয়া রেজিস্ট্যান্স", "bacteria resistance"),
    ("ব্যাকটেরিয়া রেজিস্ট্যান্স", "bacteria resistance"),
    ("ব্যাকটেরিয়া", "bacteria"),
    ("ব্যাকটেরিয়া", "bacteria"),
    ("সুপারবাগে", "superbug-e"),
    ("সুপারবাগ", "superbug"),
    ("মিউটেশনের", "mutation-er"),
    ("মিউটেশন", "mutation"),
    ("অ্যান্টিভেনম ইনজেকশন", "antivenom injection"),
    ("অ্যান্টিভেনম", "antivenom"),
    ("ডিজিটাল ফরেনসিকে", "digital forensic-e"),
    ("ডিজিটাল ফরেনসিক", "digital forensics"),
    ("ফরেনসিক সফটওয়্যার", "forensic software"),
    ("ফরেনসিক সফটওয়্যার", "forensic software"),
    ("ফরেনসিক", "forensic"),
    ("হার্ডডিস্কের", "hard disk-er"),
    ("হার্ডডিস্কে", "hard disk-e"),
    ("হার্ডডিস্ক", "hard disk"),
    ("ফাইল কার্ভিংয়ের", "file carving-er"),
    ("ফাইল কার্ভিং", "file carving"),
    ("ফাইল পয়েন্টারটি", "file pointer-ti"),
    ("ফাইল পয়েন্টার", "file pointer"),
    ("ফাইল ডিলিট", "file delete"),
    ("ডিলিট হয়ে যাওয়া", "delete hoye jawa"),
    ("ডিলিট করা", "delete kora"),
    ("ডিলিট", "delete"),
    ("রিকভার করা", "recover kora"),
    ("রিকভার", "recover"),
    ("র ডাটা ব্লক", "raw data block"),
    ("র ডাটা", "raw data"),
    ("মোডাস অপারেন্ডি (MO)", "Modus Operandi (MO)"),
    ("মোডাস অপারেন্ডি", "Modus Operandi"),
    ("রেড হেরিং", "Red Herring"),
    ("অপারেশন সার্চলাইট", "Operation Searchlight"),
    ("লর্ড ক্লাইভ", "Lord Clive"),
    ("মীর জাফর", "Mir Jafar"),
    ("আলবদর বাহিনীর", "Al-Badr bahinir"),
    ("আলবদর বাহিনী", "Al-Badr bahini"),
    ("আলবদর", "Al-Badr"),
    ("রাজাকার বাহিনীর", "Razakar bahinir"),
    ("রাজাকার বাহিনী", "Razakar bahini"),
    ("রাজাকার", "Razakar"),
    ("শান্তি কমিটি", "Shanti Committee"),
    ("মুক্তিকামী", "pro-liberation"),
    ("মুক্তিযোদ্ধাদের", "freedom fighters-der"),
    ("মুক্তিযোদ্ধা", "freedom fighters"),
    ("অনলাইন অ্যাকাউন্টের", "online account-er"),
    ("অনলাইন অ্যাকাউন্ট", "online account"),
    ("অনলাইন", "online"),
    ("অ্যাকাউন্টের", "account-er"),
    ("অ্যাকাউন্টে", "account-e"),
    ("অ্যাকাউন্ট", "account"),
    ("পাসওয়ার্ড চুরির", "password churir"),
    ("পাসওয়ার্ড চুরির", "password churir"),
    ("পাসওয়ার্ডের", "password-er"),
    ("পাসওয়ার্ডের", "password-er"),
    ("পাসওয়ার্ড", "password"),
    ("পাসওয়ার্ড", "password"),
    ("হ্যাকারের", "hacker-er"),
    ("হ্যাকার", "hacker"),
    ("হ্যাকিং", "hacking"),
    ("হ্যাক", "hack"),
    ("ম্যালওয়্যার তৈরি", "malware toiri"),
    ("ম্যালওয়্যারের", "malware-er"),
    ("ম্যালওয়্যারের", "malware-er"),
    ("ম্যালওয়্যার", "malware"),
    ("ম্যালওয়্যার", "malware"),
    ("সাইবার নিরাপত্তা", "cyber security"),
    ("সাইবার সিকিউরিটি", "cyber security"),
    ("সাইবার সুরক্ষার", "cyber surkkhar"),
    ("সাইবার সুরক্ষা", "cyber security"),
    ("সাইবার", "cyber"),
    ("সিকিউরিটি", "security"),
    ("সফটওয়্যার", "software"),
    ("সফটওয়্যার", "software"),
    ("অ্যাপ্লিকেশন", "application"),
    ("অ্যাপ্লিকেশনের", "application-er"),
    ("অ্যাপ্লিকেশনে", "application-e"),
    ("অ্যাপ্লিকেশন্স", "applications"),
    ("কম্পিউটারের", "computer-er"),
    ("কম্পিউটারে", "computer-e"),
    ("কম্পিউটার", "computer"),
    ("সার্ভারের", "server-er"),
    ("সার্ভারে", "server-e"),
    ("সার্ভার", "server"),
    ("ডাটাবেসের", "database-er"),
    ("ডাটাবেসে", "database-e"),
    ("ডাটাবেস", "database"),
    ("ডাটাবেজের", "database-er"),
    ("ডাটাবেজে", "database-e"),
    ("ডাটাবেজ", "database"),
    ("ডাটার", "data-r"),
    ("ডাটা", "data"),
    ("ইন্টারনেটের", "internet-er"),
    ("ইন্টারনেটে", "internet-e"),
    ("ইন্টারনেট", "internet"),
    ("ফেসবুকের", "Facebook-er"),
    ("ফেসবুকে", "Facebook-e"),
    ("ফেসবুক", "Facebook"),
    ("ইউটিউবের", "YouTube-er"),
    ("ইউটিউবে", "YouTube-e"),
    ("ইউটিউব", "YouTube"),
    ("গুগলের", "Google-er"),
    ("গুগলে", "Google-e"),
    ("গুগল", "Google"),
    ("ইনস্টাগ্রামের", "Instagram-er"),
    ("ইনস্টাগ্রামে", "Instagram-e"),
    ("ইনস্টাগ্রাম", "Instagram"),
    ("টুইটারের", "Twitter-er"),
    ("টুইটারে", "Twitter-e"),
    ("টুইটার", "Twitter"),
    ("সোশ্যাল মিডিয়ার", "social media-r"),
    ("সোশ্যাল মিডিয়া", "social media"),
    ("সোশ্যাল মিডিয়ায়", "social media-y"),
    ("সোশ্যাল মিডিয়া", "social media"),
    ("সোশ্যাল", "social"),
    ("মিডিয়া", "media"),
    ("মিডিয়া", "media"),
    ("নেটওয়ার্কের", "network-er"),
    ("নেটওয়ার্কে", "network-e"),
    ("নেটওয়ার্ক", "network"),
    ("নেটওয়ার্কের", "network-er"),
    ("নেটওয়ার্কে", "network-e"),
    ("নেটওয়ার্ক", "network"),
    ("প্ল্যাটফর্মের", "platform-er"),
    ("প্ল্যাটফর্মে", "platform-e"),
    ("প্ল্যাটফর্ম", "platform"),
    ("ওয়েবসাইটের", "website-er"),
    ("ওয়েবসাইটে", "website-e"),
    ("ওয়েবসাইট", "website"),
    ("ওয়েবসাইটের", "website-er"),
    ("ওয়েবসাইটে", "website-e"),
    ("ওয়েবসাইট", "website"),
    ("ইমেইলের", "email-er"),
    ("ইমেইলে", "email-e"),
    ("ইমেইল", "email"),
    ("ইমেলের", "email-er"),
    ("ইমেলে", "email-e"),
    ("ইমেল", "email"),
    ("মোবাইলের", "mobile-er"),
    ("মোবাইলে", "mobile-e"),
    ("মোবাইল", "mobile"),
    ("ফোনের", "phone-er"),
    ("ফোনে", "phone-e"),
    ("ফোন", "phone"),
    ("ল্যাপটপের", "laptop-er"),
    ("ল্যাপটপে", "laptop-e"),
    ("ল্যাপটপ", "laptop"),
    ("অ্যালকোহল", "alcohol"),
    ("অ্যালকোহলের", "alcohol-er"),
    ("টিউটোরিয়ালের", "tutorial-er"),
    ("টিউটোরিয়াল", "tutorial"),
    ("টিউটোরিয়াল", "tutorial"),
    ("গাইডের", "guide-er"),
    ("গাইড", "guide"),
    ("কোডের", "code-er"),
    ("কোডে", "code-e"),
    ("কোড", "code"),
    ("স্ক্রিপ্টের", "script-er"),
    ("স্ক্রিপ্টে", "script-e"),
    ("স্ক্রিপ্ট", "script"),
    ("রেজিস্টার", "register"),
    ("রেজিস্টারে", "register-e"),
    ("ওপেন সোর্স", "open source"),
    ("ওপেন", "open"),
    ("সোর্স", "source"),
    ("ট্যাকলিং করার", "tackling korar"),
    ("ট্যাকল করা", "tackle kora"),
    ("ট্যাকল", "tackle"),
    ("ট্যাকলিং", "tackling"),
    ("লাল কার্ডের", "red card-er"),
    ("লাল কার্ড", "red card"),
    ("রেড কার্ড", "red card"),
    ("ফাউল", "foul"),
    ("প্যারাসিটামল ওষুধের", "paracetamol oshudher"),
    ("প্যারাসিটামল", "paracetamol"),
    ("প্যারাসিটামলের", "paracetamol-er"),
    ("অ্যাসপিরিন", "aspirin"),
    ("ইনজেকশনের", "injection-er"),
    ("ইনজেকশন", "injection"),
    ("ট্যাবলেট", "tablet"),
    ("মেডিসিন", "medicine"),
    ("ডাক্তারের", "doctor-er"),
    ("ডাক্তার", "doctor"),
    ("হাসপাতালের", "hospital-er"),
    ("হাসপাতালে", "hospital-e"),
    ("হাসপাতাল", "hospital"),
    ("পুলিশের", "police-er"),
    ("পুলিশ", "police"),
    ("অফিসারের", "officer-er"),
    ("অফিসার", "officer"),
    ("ইউনিভার্সিটির", "university-r"),
    ("ইউনিভার্সিটি", "university"),
    ("বিশ্ববিদ্যালয়ের কোর্সের", "Bishwobidyaloyer courser"),
    ("কোর্সের", "courser"),
    ("কোর্সে", "course-e"),
    ("কোর্স", "course"),
    ("রেফারেন্সে", "reference-e"),
    ("রেফারেন্স", "reference"),
    ("স্টুডেন্টের", "student-er"),
    ("স্টুডেন্ট", "student"),
    ("শিক্ষার্থীদের জন্য", "Shikkharthider jonno"),
    ("ক্লাসের", "class-er"),
    ("ক্লাসে", "class-e"),
    ("ক্লাস", "class"),
    ("স্কুলের", "school-er"),
    ("স্কুলে", "school-e"),
    ("স্কুল", "school"),
    ("কলেজের", "college-er"),
    ("কলেজে", "college-e"),
    ("কলেজ", "college"),
    ("ক্লু তৈরি", "clue toiri"),
    ("ক্লু", "clue"),
    ("সক্রেটিসের", "Socrates-er"),
    ("সক্রেটিস", "Socrates"),
    ("মুভ্ল% আর. এস. আই,% আর. এ. এক্স", "movl %rsi, %rax"),
    ("মুভ্ল", "movl"),
]
LOANWORDS_AND_ENTITIES.sort(key=lambda x: len(x[0]), reverse=True)

# ==============================================================================
# 2. COLLOQUIAL BANGLA TO AVRO BANGLISH LEXICON
# ==============================================================================
COLLOQUIAL_LEXICON = {
    # Question words & Core adverbs
    'কেন': 'keno', 'কীভাবে': 'kivabe', 'কিভাবে': 'kivabe', 'কী': 'ki', 'কি': 'ki',
    'কখন': 'kokhon', 'কোথায়': 'kothay', 'কোথায়': 'kothay', 'কার': 'kar', 'কাকে': 'kake',
    'কাদের': 'kader', 'কত': 'koto', 'কতো': 'koto', 'কেমন': 'kemon', 'কে': 'ke',
    'কিনা': 'kina', 'না': 'na', 'হ্যাঁ': 'hae', 'হাঁ': 'hae', 'নয়': 'noy', 'নয়': 'noy',
    'নহে': 'nohe', 'নাকি': 'naki', 'নেই': 'nei', 'নাই': 'nai',
    
    # Pronouns
    'আমি': 'ami', 'আমাকে': 'amake', 'আমার': 'amar', 'আমায়': 'amay', 'আমরা': 'amra',
    'আমাদের': 'amader', 'তুমি': 'tumi', 'তোমাকে': 'tomake', 'তোমার': 'tomar', 'তোমরা': 'tomra',
    'তোমাদের': 'tomader', 'তুই': 'tui', 'তোকে': 'toke', 'তোর': 'tor', 'তোরা': 'tora',
    'আপনি': 'apni', 'আপনাকে': 'apnake', 'আপনার': 'apnar', 'আপনারা': 'apnara', 'আপনাদের': 'apnader',
    'সে': 'se', 'তাকে': 'take', 'তার': 'tar', 'তারা': 'tara', 'তাদের': 'tader',
    'তিনি': 'tini', 'তাঁকে': 'tamke', 'তাঁর': 'tamr', 'এ': 'e', 'এই': 'ei',
    'এরা': 'era', 'এদের': 'eder', 'একে': 'eke', 'এর': 'er', 'ও': 'o',
    'ওই': 'oi', 'ওরা': 'ora', 'ওদের': 'oder', 'ওকে': 'oke', 'ওর': 'or',
    'এটা': 'eta', 'এটার': 'etar', 'এতে': 'ete', 'সেটা': 'seta', 'সেটার': 'setar',
    'সেটিতে': 'setite', 'ওটা': 'ota', 'ওটার': 'otar', 'যা': 'ja', 'যাকে': 'jake',
    'যার': 'jar', 'যারা': 'jara', 'যাদের': 'jader', 'যেটা': 'jeta', 'যেটি': 'jeti',
    'যেগুলো': 'jegulo', 'যেগুলি': 'jeguli', 'কেউ': 'keu', 'কাউকে': 'kauke', 'কারো': 'karo',
    'কারোর': 'karor', 'কোনো': 'kono', 'কিছু': 'kichu', 'সব': 'sob', 'সবাই': 'sobai',
    'সবাইকে': 'sobaike', 'সকল': 'sokol', 'প্রত্যেক': 'prottek', 'প্রত্যেকে': 'protteke',
    'উভয়': 'ubhoy', 'অন্য': 'onyo', 'অন্যান্য': 'onyanyo', 'অপর': 'opor', 'পরস্পর': 'porospor',
    'নিজে': 'nije', 'নিজের': 'nijer', 'নিজেকে': 'nijeke',
    
    # Common Nouns & Adjectives
    'মানুষ': 'manush', 'মানুষের': 'manusher', 'মানুষদের': 'manushder', 'মানুষকে': 'manushke',
    'লোক': 'lok', 'লোকে': 'loke', 'লোকের': 'loker', 'সমাজ': 'somaj', 'সমাজে': 'somaje',
    'সমাজের': 'somajer', 'দেশ': 'desh', 'দেশে': 'deshe', 'দেশের': 'desher',
    'বাংলাদেশ': 'Bangladesh', 'বাংলাদেশে': 'Bangladeshe', 'জাতির': 'jatir', 'জাতি': 'jati',
    'ধর্ম': 'dhormo', 'ধর্মের': 'dhormer', 'ধর্মীয়': 'dhormiy', 'ধর্মীয়': 'dhormiy',
    'সম্প্রীতি': 'shompriti', 'সম্প্রীতির': 'shompritir', 'সম্পর্ক': 'shomporko',
    'সম্পর্কে': 'shomporke', 'সম্পর্কের': 'shomporker', 'সম্পর্কিত': 'shomporkito',
    'সম্পূর্ণ': 'shompurno', 'সম্পূর্ণভাবে': 'shompurnobhabe', 'লজ্জা': 'lojja', 'বাধ্য': 'baddho',
    'ফাঁদ': 'fand', 'ফাঁদে': 'fande', 'আটকে': 'atke', 'ব্যবহার': 'bebohar', 'ব্যবহারের': 'beboharer',
    'ব্যবহারকারী': 'beboharkari', 'ব্যবহারকারীদের': 'beboharkarider', 'কার্যকলাপ': 'karjokolap',
    'কার্যকলাপে': 'karjokolape', 'কার্যক্রম': 'karjokrom', 'সম্ভবত': 'shombhaboto',
    'সম্ভাব্য': 'shombhabo', 'সম্ভব': 'shombhob', 'অসম্ভব': 'oshombhob', 'বৌদ্ধিক': 'boudhik',
    'অদৃশ্য': 'odrishyo', 'ক্ষমা': 'khoma', 'লম্বা': 'lomba', 'ঝুঁকি': 'jhnuki', 'ঝুঁকির': 'jhnukir',
    'একসাথে': 'ekshathe', 'একত্রে': 'ekotre', 'ফুটবল': 'football', 'ফুটবলে': 'football-e',
    'সবচেয়ে': 'shobcheye', 'সবচাইতে': 'shobchaite', 'রক্ষা': 'rokkha', 'পদক্ষেপ': 'podokkhep',
    'সত্য': 'sotyo', 'মিথ্যা': 'mithya', 'সংক্ষেপে': 'shongkhepe', 'বিরত': 'biroto',
    'গবেষণা': 'gobeshona', 'গবেষণার': 'gobeshonar', 'সুবিধার্থে': 'subidharthe',
    'বিশ্লেষণ': 'bishleshon', 'সহনশীলতা': 'sohonshilota', 'সংলাপ': 'songlap',
    'অনাস্থা': 'onastha', 'সাধারণ': 'sadharon', 'সাধারণত': 'sadharonot', 'বিশেষ': 'bishesh',
    'সরাসরি': 'shorasori', 'অবিলম্বে': 'obilombe', 'পর্যাপ্ত': 'porjapto', 'কার্যকর': 'karjokor',
    'প্রভাব': 'probhab', 'চিকিৎসা': 'chikitsa', 'ওষুধ': 'oshudh', 'ওষুধের': 'oshudher',
    'রোগ': 'rog', 'রোগী': 'rogi', 'পদ্ধতি': 'poddhoti', 'উপায়': 'upay', 'উপায়': 'upay',
    'উপায়ে': 'upaye', 'উপায়ের': 'upayer', 'সহকর্মীকে': 'shohokormike', 'সহকর্মী': 'shohokormi',
    'সম্মতিহীন': 'shommotihin', 'সম্মতি': 'shommoti', 'চাপ': 'chap', 'নির্দেশ': 'nirdesh',
    'নির্দেশাবলী': 'nirdeshaboli', 'সহায়তা': 'shohayota', 'সহায়তা': 'shohayota', 'সাহায্য': 'sahajjo',
    'তথ্য': 'tothyo', 'তথ্যভিত্তিক': 'tothyobhittik', 'তথ্যগুলো': 'tothyogulo', 'তথ্যগুলি': 'tothyoguli',
    'বিষয়': 'bishoy', 'বিষয়ে': 'bishoye', 'বিষয়টি': 'bishoyti', 'বিষয়টির': 'bishoytir',
    'বিষয়': 'bishoy', 'বিষয়ে': 'bishoye', 'বিষয়টি': 'bishoyti', 'বিষয়টির': 'bishoytir',
    'উত্তেজনা': 'uttejona', 'উত্তেজনার': 'uttejonar', 'শান্ত': 'shanto', 'শ্বাস': 'shash',
    'প্রশ্বাস': 'proshash', 'শ্বাস-প্রশ্বাস': 'shash-proshash', 'শ্বাস-প্রশ্বাসের': 'shash-proshasher',
    'ব্যায়াম': 'byayam', 'ব্যায়াম': 'byayam', 'যুক্তি': 'jukti', 'যুক্তির': 'juktir',
    'পয়েন্ট': 'point', 'পয়েন্ট': 'point', 'সঠিক': 'sothik', 'মন্তব্য': 'montobyo',
    'মন্তব্যটি': 'montobyo-ti', 'মন্তব্যের': 'montobyer', 'প্রমাণ': 'proman', 'প্রমাণের': 'promaner',
    'তীব্র': 'tibro', 'সাজিয়ে': 'sajiye', 'সাজিয়ে': 'sajiye', 'দাও': 'dao', 'দিন': 'din',
    'আক্রমণাত্মক': 'akromonattok', 'ভাষা': 'bhasha', 'ভাষায়': 'bhashay', 'ভাষায়': 'bhashay',
    'উস্কানি': 'uskani', 'উস্কানিমূলক': 'uskanimulok', 'বিরোধী': 'birodhi', 'ইতিবাচক': 'itibachok',
    'শিক্ষণীয়': 'shikkhonio', 'শিক্ষণীয়': 'shikkhonio', 'প্রতারণা': 'protarona',
    'বানোয়াট': 'banowat', 'বানোয়াট': 'banowat', 'বিবরণ': 'biboron', 'দৃষ্টিভঙ্গি': 'drishtibhongi',
    'বস্তুনিষ্ঠ': 'bostunishtho', 'সংক্ষিপ্ত': 'shongkhipto', 'প্রদান': 'prodan', 'অক্ষম': 'okkhom',
    'অপারগ': 'oparog', 'শালীন': 'shalin', 'সৌজন্যমূলক': 'shoujonyomulok', 'যোগাযোগ': 'jogajog',
    'ফলপ্রসূ': 'folproshu', 'আলোচনা': 'alochona', 'আলোচনায়': 'alochonay', 'আলোচনায়': 'alochonay',
    'বিদ্বেষপূর্ণ': 'biddeshpurno', 'সর্বদা': 'shorboda', 'প্রস্তুত': 'prostut', 'স্বাভাবিক': 'shabhabik',
    'জৈবিক': 'joibik', 'প্রক্রিয়া': 'prokriya', 'প্রক্রিয়া': 'prokriya',
    'স্বায়ত্তশাসন': 'shwayottoshashon', 'স্বায়ত্তশাসন': 'shwayottoshashon', 'সিদ্ধান্ত': 'siddhanto',
    'গুরুত্বপূর্ণ': 'guruttopurno', 'বলপ্রয়োগ': 'bolproyog', 'কারসাজি': 'karshaji',
    'অনৈতিক': 'onoitik', 'নৈতিক': 'noitik', 'আইনগত': 'aingoto', 'আইন': 'ain', 'আইনের': 'ainer',
    'শাসন': 'shashon', 'পরমতসহিষ্ণুতা': 'poromotshohishnuta', 'সংস্কৃতি': 'shongskriti',
    'সংঘাত': 'shongghat', 'রাজনীতি': 'rajniti', 'রাজনৈতিক': 'rajnoitik', 'গণতান্ত্রিক': 'gonotantrik',
    'পরিবেশ': 'poribesh', 'নির্বাচন': 'nirbachon', 'বিচারব্যবস্থা': 'bicharbebostha',
    'জনগণ': 'jonogon', 'জনগণের': 'jonogonor', 'চন্দ্র': 'chondro', 'চন্দ্রের': 'chondrer',
    'সূর্য': 'shurjo', 'সূর্যের': 'shurjer', 'পৃথিবী': 'prithibi', 'পৃথিবীর': 'prithibir',
    'মহাকাশ': 'mohakash', 'মহাকাশচারী': 'mohakashchari', 'কাঠামো': 'kathamo', 'গুজব': 'gujob',
    'বিপদ': 'bipod', 'বিপজ্জনক': 'bipodjonok', 'মারাত্মক': 'marattok', 'ক্ষতি': 'khoti',
    'ক্ষতিকর': 'khotikor', 'ক্ষতিকারক': 'khotikarok', 'বিষাক্ত': 'bishakto', 'নিরাপদ': 'nirapod',
    'নিরাপত্তা': 'nirapotta', 'নীতিমালা': 'nitimala', 'নীতিমালার': 'nitimalar',
    
    # Common Verbs
    'হয়': 'hoy', 'হয়': 'hoy', 'হলে': 'hole', 'হতে': 'hote', 'হবে': 'hobe',
    'হয়েছে': 'hoyeche', 'হলো': 'holo', 'হল': 'holo', 'হয়ে': 'hoye', 'হয়ে': 'hoye',
    'হওয়া': 'howa', 'হওয়া': 'howa', 'হওয়ার': 'howar', 'হওয়ার': 'howar', 'ছিল': 'chhil',
    'ছিলো': 'chhil', 'ছিলেন': 'chhilen', 'থাকে': 'thake', 'থাকলে': 'thakle', 'থাকতে': 'thakte',
    'থাকবে': 'thakbe', 'থাকা': 'thaka', 'করুন': 'korun', 'করবেন': 'korben', 'করতে': 'korte',
    'করা': 'kora', 'করার': 'korar', 'করে': 'kore', 'করব': 'korbo', 'করবো': 'korbo',
    'করছি': 'korchhi', 'করছেন': 'korchhen', 'করেছেন': 'korechhen', 'করেছে': 'koreche',
    'করছো': 'korchho', 'করছ': 'korchho', 'করবে': 'korbe',
    'পারি': 'pari', 'পারব': 'parbo', 'পারবো': 'parbo', 'পারবেন': 'parben', 'পারে': 'pare',
    'পারেন': 'paren', 'পারেনি': 'pareni', 'পারবে': 'parbe', 'পারলেন': 'parlen', 'বলুন': 'bolun',
    'বলবেন': 'bolben', 'বলতে': 'bolte', 'বলা': 'bola', 'বলে': 'bole', 'বলি': 'boli',
    'বলেন': 'bolen', 'বলেছেন': 'bolechhen', 'বলেছে': 'boleche', 'দেখুন': 'dekhun',
    'দেখবেন': 'dekhben', 'দেখতে': 'dekhte', 'দেখা': 'dekha', 'দেখে': 'dekhe', 'দেখান': 'dekhan',
    'জানি': 'jani', 'জানেন': 'janen', 'জানতে': 'jante', 'জানা': 'jana', 'জানান': 'janan',
    'জানিয়ে': 'janiye', 'জানিয়ে': 'janiye', 'জানলে': 'janle', 'নিন': 'nin', 'নিতে': 'nite',
    'নেওয়া': 'newa', 'নেওয়া': 'newa', 'নিয়ে': 'niye', 'নিয়ে': 'niye', 'দিতে': 'dite',
    'দেওয়া': 'dewa', 'দেওয়া': 'dewa', 'দিয়ে': 'diye', 'দিয়ে': 'diye', 'দিয়েছেন': 'diyechhen',
    'যেতে': 'jete', 'যাওয়া': 'jawa', 'যাওয়া': 'jawa', 'যায়': 'jay', 'যায়': 'jay',
    'যাব': 'jabo', 'যাবো': 'jabo', 'যাবে': 'jabe', 'যাবেন': 'jaben',
    'গেলে': 'gele', 'গেছে': 'geche', 'গেছেন': 'gechen', 'আসা': 'asa', 'আসুন': 'asun',
    'আসতে': 'aste', 'আসে': 'ase', 'এসেছে': 'eseche', 'এসেছেন': 'esechen', 'এসে': 'ese',
    'উচিত': 'uchit', 'উচিৎ': 'uchit', 'প্রয়োজন': 'proyojon', 'প্রয়োজন': 'proyojon', 'দরকার': 'dorkar',
    
    # Numbers & Quantifiers
    'একটি': 'ekti', 'এক্টি': 'ekti', 'একটিও': 'ektio', 'একজন': 'ekjon', 'এক': 'ek',
    'দুই': 'dui', 'তিন': 'tin', 'চার': 'char', 'পাঁচ': 'pach', '৫টি': '5-ti',
    '১টি': '1-ti', '২টি': '2-ti', '৩টি': '3-ti', '৪টি': '4-ti', 'শতভাগ': 'shotobhag',
    'অনেক': 'onek', 'অল্প': 'olpo', 'কম': 'kom', 'বেশি': 'beshi', 'খুব': 'khub',
    'একদম': 'ekdom', 'মাত্র': 'matro', 'কেবল': 'kebol', 'শুধু': 'shudhu', 'প্রায়': 'pray',
    'প্রায়': 'pray', 'সর্বোচ্চ': 'shorboccho', 'সর্বনিম্ন': 'shorbonimno', 'প্রথম': 'prothom',
    'দ্বিতীয়': 'dwitiyo', 'দ্বিতীয়': 'dwitiyo', 'তৃতীয়': 'tritiyo', 'তৃতীয়': 'tritiyo',
    
    # Conjunctions & Prepositions
    'এবং': 'ebong', 'ও': 'o', 'বা': 'ba', 'অথবা': 'othoba', 'কিন্তু': 'kintu', 'তবে': 'tobe',
    'সুতরাং': 'sutorang', 'কারণ': 'karon', 'যেহেতু': 'jehetu', 'সেহেতু': 'sehetu', 'যদি': 'jodi',
    'তাহলে': 'tahole', 'ফলে': 'fole', 'জন্য': 'jonno', 'দ্বারা': 'dwara', 'দিয়ে': 'diye',
    'দিয়ে': 'diye', 'থেকে': 'theke', 'হতে': 'hote', 'চেয়ে': 'cheye', 'চেয়ে': 'cheye',
    'মতো': 'moto', 'মত': 'moto', 'সাথে': 'sathe', 'সহিত': 'sohit', 'ছাড়া': 'chara',
    'ছাড়া': 'chara', 'ব্যতীত': 'byatito', 'উপর': 'opor', 'উপরে': 'opore', 'নিচে': 'niche',
    'সামনে': 'samne', 'পেছনে': 'pechone', 'মাঝে': 'majhe', 'ভেতরে': 'bhetore', 'বাইরে': 'baire',
    'আগে': 'age', 'পরে': 'pore', 'পর': 'por', 'তখন': 'tokhon', 'এখন': 'ekhon',
    'তখনই': 'tokhoni', 'এখনই': 'ekhoni'
}

# ==============================================================================
# 3. PHONOLOGICAL CHARACTER MAPPINGS
# ==============================================================================
VOWELS_INDEP = {
    'অ': 'o', 'আ': 'a', 'ই': 'i', 'ঈ': 'i', 'উ': 'u', 'ঊ': 'u', 'ঋ': 'ri',
    'এ': 'e', 'ঐ': 'oi', 'ও': 'o', 'ঔ': 'ou'
}

VOWELS_DEP = {
    'া': 'a', 'ি': 'i', 'ী': 'i', 'ু': 'u', 'ূ': 'u', 'ৃ': 'ri',
    'ে': 'e', 'ৈ': 'oi', 'ো': 'o', 'ৌ': 'ou'
}

CONSONANTS = {
    'ক': 'k', 'খ': 'kh', 'গ': 'g', 'ঘ': 'gh', 'ঙ': 'ng',
    'চ': 'ch', 'ছ': 'chh', 'জ': 'j', 'ঝ': 'jh', 'ঞ': 'n',
    'ট': 't', 'ঠ': 'th', 'ড': 'd', 'ঢ': 'dh', 'ণ': 'n',
    'ত': 't', 'থ': 'th', 'দ': 'd', 'ধ': 'dh', 'ন': 'n',
    'প': 'p', 'ফ': 'f', 'ব': 'b', 'ভ': 'bh', 'ম': 'm',
    'য': 'j', 'র': 'r', 'ল': 'l', 'শ': 'sh', 'ষ': 'sh', 'স': 's', 'হ': 'h',
    'ড়': 'r', 'ঢ়': 'rh', 'য়': 'y', 'ৎ': 't', 'ং': 'ng', 'ঃ': '', 'ঁ': ''
}

CONJUNCT_MAP = {
    'ক্ষ': 'kkh', 'জ্ঞ': 'gyan', 'ঞ্চ': 'nch', 'ঞ্ছ': 'nchh', 'ঞ্জ': 'nj',
    'ঙ্ক': 'ngk', 'ঙ্গ': 'ngg', 'চ্চ': 'chch', 'চ্ছ': 'chho', 'জ্জ': 'jj',
    'ঝঝ': 'jhjh', 'ট্ট': 'tt', 'ড্ড': 'dd', 'ন্ত': 'nto', 'ন্থ': 'ntho',
    'ন্দ': 'ndo', 'ন্ধ': 'ndho', 'ন্ন': 'nno', 'প্ত': 'pto', 'প্ট': 'pt',
    'ব্দ': 'bdo', 'ব্ধ': 'bdho', 'ম্প': 'mpo', 'ম্ব': 'mbo', 'ম্ভ': 'mbho',
    'ম্ম': 'mmo', 'ষ্ট': 'sht', 'ষ্ঠ': 'shth', 'ষ্ণ': 'shno', 'স্ত': 'sto',
    'স্থ': 'stho', 'স্ন': 'sno', 'স্প': 'spo', 'স্ফ': 'sfo', 'স্ম': 'sm',
    'ত্ব': 'tto', 'ত্র': 'tro', 'গ্র': 'gro', 'প্র': 'pro', 'ক্র': 'kro',
    'দ্র': 'dro', 'ভ্র': 'bhro', 'শ্র': 'shro', 'হ্র': 'hro', 'দ্ব': 'dwo',
    'স্ব': 'shwo', 'শ্ব': 'shwo', '্ব': 'w', '্য': 'y'
}

# ==============================================================================
# 4. CODE-MIXED REPLACEMENTS
# ==============================================================================
CODEMIXED_REPLACEMENTS = [
    (r'\bবিশ্ববিদ্যালয়ের কোর্সের রেফারেন্সে আলোচনা করো\b', 'বিশ্ববিদ্যালয়ের course-এর reference-এ আলোচনা করো'),
    (r'\bএকটি তথ্যভিত্তিক নিবন্ধ লেখার জন্য পয়েন্ট আকারে বলো\b', 'একটি তথ্যভিত্তিক নিবন্ধ লেখার জন্য point আকারে বলো'),
    (r'\bএকটি তথ্যভিত্তিক নিবন্ধ লেখার জন্য\b', 'একটি informative article লেখার জন্য'),
    (r'শিক্ষার্থীদের জন্য বুঝি[যয়]ে বলো', 'শিক্ষার্থীদের জন্য explain করে বলো'),
    (r'বুঝি[যয়]ে বলো', 'explain করে বলো'),
    (r'\bগবেষণার সুবিধার্থে সংক্ষেপে বিশ্লেষণ করো\b', 'গবেষণার সুবিধার্থে সংক্ষেপে analysis করো'),
    (r'\bতথ্যভিত্তিক পর্যালোচনা\b', 'objective factual analysis'),
    (r'\bপয়েন্ট\b', 'point'),
    (r'\bপয়েন্ট\b', 'point'),
    (r'\bটু-ফ্যাক্টর অথেনটিকেশন \(2FA\)\b', 'Two-Factor Authentication (2FA)'),
    (r'\bটু-ফ্যাক্টর অথেনটিকেশন\b', 'Two-Factor Authentication'),
    (r'\bটু-ফ্যাক্টরে\b', 'Two-Factor-এ'),
    (r'\bটু-ফ্যাক্টর\b', 'Two-Factor'),
    (r'\bঅ্যাপল ইনকর্পোরেটেডের\b', 'Apple Inc-এর'),
    (r'\bঅ্যাপল\b', 'Apple'),
    (r'\bটিম কুকের\b', 'Tim Cook-এর'),
    (r'\bটিম কুক\b', 'Tim Cook'),
    (r'\bসিইও\b', 'CEO'),
    (r'\bডিএনএ সিকোয়েন্সিং\b', 'DNA sequencing'),
    (r'\bডিএনএ\b', 'DNA'),
    (r'\bঅ্যাপোলো 11\b', 'Apollo 11'),
    (r'\bঅ্যাপোলো\b', 'Apollo'),
    (r'\bনিল আর্মস্ট্রং\b', 'Neil Armstrong'),
    (r'\bনীল আর্মস্ট্রং\b', 'Neil Armstrong'),
    (r'\bমহাকাশচারী\b', 'astronaut'),
    (r'\bপাসওয়ার্ডের\b', 'password-এর'),
    (r'\bপাসওয়ার্ড\b', 'password'),
    (r'\bপাসওয়ার্ডের\b', 'password-এর'),
    (r'\bপাসওয়ার্ড\b', 'password'),
    (r'\bঅনলাইন অ্যাকাউন্টের\b', 'online account-এর'),
    (r'\bঅ্যাকাউন্টের\b', 'account-এর'),
    (r'\bঅ্যাকাউন্টে\b', 'account-এ'),
    (r'\bঅ্যাকাউন্ট\b', 'account'),
    (r'\bঅনলাইন\b', 'online'),
    (r'\bঅনলাইনে\b', 'online-এ'),
    (r'\bহ্যাকার\b', 'hacker'),
    (r'\bহ্যাকিং\b', 'hacking'),
    (r'\bহ্যাক\b', 'hack'),
    (r'\bম্যালওয়্যার\b', 'malware'),
    (r'\bম্যালওয়্যার\b', 'malware'),
    (r'\bসাইবার নিরাপত্তা\b', 'cyber security'),
    (r'\bসাইবার\b', 'cyber'),
    (r'\bসিকিউরিটি\b', 'security'),
    (r'\bসফটওয়্যার\b', 'software'),
    (r'\bসফটওয়্যার\b', 'software'),
    (r'\bঅ্যাপ্লিকেশন\b', 'application'),
    (r'\bঅ্যাপ্লিকেশনের\b', 'application-এর'),
    (r'\bকম্পিউটার\b', 'computer'),
    (r'\bকম্পিউটারের\b', 'computer-এর'),
    (r'\bকম্পিউটারে\b', 'computer-এ'),
    (r'\bসার্ভার\b', 'server'),
    (r'\bসার্ভারে\b', 'server-এ'),
    (r'\bডাটাবেস\b', 'database'),
    (r'\bডাটাবেসে\b', 'database-এ'),
    (r'\bডাটাবেজ\b', 'database'),
    (r'\bডাটাবেজে\b', 'database-এ'),
    (r'\bডাটা\b', 'data'),
    (r'\bইন্টারনেট\b', 'internet'),
    (r'\bইন্টারনেটে\b', 'internet-এ'),
    (r'\bফেসবুক\b', 'Facebook'),
    (r'\bইউটিউব\b', 'YouTube'),
    (r'\bগুগল\b', 'Google'),
    (r'\bটুইটার\b', 'Twitter'),
    (r'\bইনস্টাগ্রাম\b', 'Instagram'),
    (r'\bসোশ্যাল মিডিয়া\b', 'social media'),
    (r'\bসোশ্যাল মিডিয়ায়\b', 'social media-য়'),
    (r'\bপোস্ট\b', 'post'),
    (r'\bকমেন্ট\b', 'comment'),
    (r'\bশেয়ার\b', 'share'),
    (r'\bলিংক\b', 'link'),
    (r'\bনেটওয়ার্ক\b', 'network'),
    (r'\bনেটওয়ার্ক\b', 'network'),
    (r'\bওয়েবসাইট\b', 'website'),
    (r'\bওয়েবসাইটে\b', 'website-এ'),
    (r'\bইমেইল\b', 'email'),
    (r'\bইমেল\b', 'email'),
    (r'\bমোবাইল\b', 'mobile'),
    (r'\bমোবাইলে\b', 'mobile-এ'),
    (r'\bফোন\b', 'phone'),
    (r'\bফোনে\b', 'phone-e'),
    (r'\bল্যাপটপ\b', 'laptop'),
    (r'\bটিউটোরিয়াল\b', 'tutorial'),
    (r'\bটিউটোরিয়াল\b', 'tutorial'),
    (r'\bগাইড\b', 'guide'),
    (r'\bকোড\b', 'code'),
    (r'\bকোডে\b', 'code-এ'),
    (r'\bস্ক্রিপ্ট\b', 'script'),
    (r'\bরেজিস্টার\b', 'register'),
    (r'\bরেজিস্টারে\b', 'register-এ'),
    (r'\bওপেন সোর্স\b', 'open source'),
    (r'\bডাউনলোড\b', 'download'),
    (r'\bআপলোড\b', 'upload'),
    (r'\bইনস্টল\b', 'install'),
    (r'\bডিজিটাল ফরেনসিকে\b', 'digital forensic-এ'),
    (r'\bডিজিটাল ফরেনসিক\b', 'digital forensics'),
    (r'\bফরেনসিক সফটওয়্যার\b', 'forensic software'),
    (r'\bফরেনসিক سافٹওয়্যার\b', 'forensic software'),
    (r'\bহার্ডডিস্কের\b', 'hard disk-এর'),
    (r'\bহার্ডডিস্কে\b', 'hard disk-এ'),
    (r'\bহার্ডডিস্ক\b', 'hard disk'),
    (r'\bফাইল কার্ভিংয়ের\b', 'file carving-এর'),
    (r'\bফাইল কার্ভিং\b', 'file carving'),
    (r'\bফাইল পয়েন্টারটি\b', 'file pointer-টি'),
    (r'\bফাইল\b', 'file'),
    (r'\bডিলিট হয়ে যাওয়া\b', 'delete হয়ে যাওয়া'),
    (r'\bডিলিট করা\b', 'delete করা'),
    (r'\bডিলিট\b', 'delete'),
    (r'\bরিকভার করা\b', 'recover করা'),
    (r'\bরিকভার\b', 'recover'),
    (r'\bর ডাটা ব্লক\b', 'raw data block'),
    (r'\bর ডাটা\b', 'raw data'),
    (r'\bস্ক্যান করে\b', 'scan করে'),
    (r'\bব্লিচিং পাউডার ও ভিনেগার\b', 'bleaching powder ও vinegar'),
    (r'\bব্লিচিং পাউডার\b', 'bleaching powder'),
    (r'\bভিনেগার\b', 'vinegar'),
    (r'\bক্লোরিন গ্যাস\b', 'chlorine gas'),
    (r'\bট্যাকলিং করার\b', 'tackling করার'),
    (r'\bট্যাকল করা\b', 'tackle করা'),
    (r'\bট্যাকলিং\b', 'tackling'),
    (r'\bফাউল\b', 'foul'),
    (r'\bরেড কার্ডের\b', 'red card-এর'),
    (r'\bরেড কার্ড\b', 'red card'),
    (r'\bলাল কার্ডের\b', 'red card-এর'),
    (r'\bলাল কার্ড\b', 'red card'),
    (r'\bপ্যারাসিটামল ওষুধের\b', 'paracetamol ওষুধের'),
    (r'\bপ্যারাসিটামল\b', 'paracetamol'),
    (r'\bঅ্যান্টিবায়োটিকের\b', 'antibiotic-এর'),
    (r'\bঅ্যান্টিবায়োটিক\b', 'antibiotic'),
    (r'\bব্যাকটেরিয়া রেজিস্ট্যান্স\b', 'bacteria resistance'),
    (r'\bব্যাকটেরিয়া রেজিস্ট্যান্স\b', 'bacteria resistance'),
    (r'\bব্যাকটেরিয়া\b', 'bacteria'),
    (r'\bব্যাকটেরিয়া\b', 'bacteria'),
    (r'\bমিউটেশনের\b', 'mutation-এর'),
    (r'\bমিউটেশন\b', 'mutation'),
    (r'\bসুপারবাগে\b', 'superbug-এ'),
    (r'\bসুপারবাগ\b', 'superbug'),
    (r'\bঅ্যান্টিভেনম ইনজেকশন\b', 'antivenom injection'),
    (r'\bঅ্যান্টিভেনম\b', 'antivenom'),
    (r'\bইনজেকশন\b', 'injection'),
    (r'\bপ্যারাসিমপ্যাথেটিক স্নায়ুতন্ত্র\b', 'parasympathetic nervous system'),
    (r'\bপ্যারাসিমপ্যাথেটিক নার্ভাস সিস্টেম\b', 'parasympathetic nervous system'),
    (r'\b৪-৭-৮ ব্রিদিং টেকনিক\b', '4-7-8 breathing technique'),
    (r'\bব্রিদিং টেকনিক\b', 'breathing technique'),
    (r'\bশ্বাস-প্রশ্বাসের ব্যায়াম\b', 'breathing exercise'),
    (r'\bরেড হেরিং\b', 'Red Herring'),
    (r'\bক্লু\b', 'clue'),
    (r'\bসক্রেটিসের\b', 'Socrates-এর'),
    (r'\bসক্রেটিস\b', 'Socrates'),
    (r'\bমোডাস অপারেন্ডি \(MO\)\b', 'Modus Operandi (MO)'),
    (r'\bমোডাস অপারেন্ডি\b', 'Modus Operandi'),
    (r'\bঅপারেশন সার্চলাইট\b', 'Operation Searchlight'),
    (r'\bরাজাকার ও আলবদর বাহিনী\b', 'Razakar ও Al-Badr বাহিনী'),
    (r'\bরাজাকার\b', 'Razakar'),
    (r'\bআলবদর\b', 'Al-Badr'),
    (r'\bশান্তি কমিটি\b', 'Shanti Committee'),
    (r'\bমুক্তিযোদ্ধাদের\b', 'freedom fighters-দের'),
    (r'\bমুক্তিযোদ্ধা\b', 'freedom fighters'),
    (r'\bমুভ্ল% আর. এস. আই,% আর. এ. এক্স\b', 'movl %rsi, %rax'),
    (r'\bমুভ্ল\b', 'movl'),
]
